// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDL9ULrtMArGyaVo3d0fgQDgWRW97RpEY',
    appId: '1:860854562070:web:c6449c4706ec2510937437',
    messagingSenderId: '860854562070',
    projectId: 'teen-splah',
    authDomain: 'teen-splah.firebaseapp.com',
    storageBucket: 'teen-splah.appspot.com',
    measurementId: 'G-7K0NS4SG5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6i0xCXzDlsQrox41RonoulkeNZqM1YY',
    appId: '1:860854562070:android:16ae49ab40159cc1937437',
    messagingSenderId: '860854562070',
    projectId: 'teen-splah',
    storageBucket: 'teen-splah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-_CXUAaBBq51TBQa4wKai8y2MEtRdEt4',
    appId: '1:860854562070:ios:f79b062a0932e514937437',
    messagingSenderId: '860854562070',
    projectId: 'teen-splah',
    storageBucket: 'teen-splah.appspot.com',
    iosBundleId: 'com.example.teenSplash',
  );
}
